dataset:
  batch_size: 128
  name: mnist
loss:
  name: crossentropy
model:
  name: ParametrizedMLP
  params:
    activation: ReLU
    hidden_dim: 256
    input_dim: 784
    num_layers: 8
optimizer:
  name: adam
  params:
    lr: 0.001
    weight_decay: 1e-5
output_dir: outputs/experiments\ParametrizedMLP_depth8_20250428_192830
project_name: MLP_vs_ResidualMLP
trainer:
  device: cuda
  epochs: 30
  mixed_precision: true
  patience: 5
  run_name: ParametrizedMLP_depth8_20250428_192830
  use_wandb: true
