model:
  name: ResidualCNN
  params:
    num_classes: 100
    depth: 32
    width: 64

trainer:
  run_name: "cnn_finetune_progressive_adam"
  epochs: 30
  device: cuda
  patience: 10
  mixed_precision: True
  use_wandb: True
  resume: True
  pretrained_checkpoint: residualcnn_checkpoint.pth
  freeze_backbone: progressive
  unfreeze_at_epochs: [10, 20]

optimizer:
  name: Adam
  lr: 0.0003
  weight_decay: 1e-4

loss:
  name: CrossEntropy

scheduler:
  name: StepLR
  params:
    step_size: 30
    gamma: 0.1

project_name: cifar100_finetune
output_dir: outputs/finetune

dataset: 
  name: "cifar100"
  batch_size: 16
  num_workers: 4
  test_size: 0.1
  val_size: 0.1