model:
  name: ResidualCNN
  num_classes: 100
  depth: 32
  width: 64

trainer:
  epochs: 100
  device: cuda
  patience: 10
  mixed_precision: True
  use_wandb: True
  resume: False
  pretrained_checkpoint: residualcnn_checkpoint.pth
  freeze_backbone: False

optimizer:
  name: Adam
  lr: 0.0001
  weight_decay: 1e-4

loss:
  name: CrossEntropyLoss

scheduler:
  name: StepLR
  step_size: 30
  gamma: 0.1

project_name: cifar100_finetune
output_dir: output/finetune
